spring:
  application:
    name: sca-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:38848
        username: nacos
        password: nacos
  insight:
    server-url: http://localhost:9966

server:
  port: 18082
