spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-standalone:8848
        username: nacos
        password: nacOsdev316
  insight:
    server-url: http://insight-server:9966
    diagnostic-logs: false

server:
  address: 0.0.0.0
