spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-standalone:8848
        username: nacos
        password: nacos
  insight:
    diagnostic-logs: false

server:
  address: 0.0.0.0
