spring:
  main:
    web-application-type: reactive
  application:
    name: sca-gateway
  cloud:
    nacos:
      discovery:
        # 本地：宿主机映射端口（nacos-standalone -p 38848:8848）
        server-addr: 127.0.0.1:38848
        username: nacos
        password: nacOsdev316
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://sca-order
              predicates:
                - Path=/order/**
            - id: product-service
              uri: lb://sca-product
              predicates:
                - Path=/product/**
            - id: user-service
              uri: lb://sca-user
              predicates:
                - Path=/user/**
            - id: loyalty-service
              uri: lb://sca-loyalty
              predicates:
                - Path=/loyalty/**
  insight:
    server-url: http://localhost:9966

server:
  port: 18080
