# Docker：WebFlux 网关；Nacos 使用本机已启动的 nacos-standalone（网络 my-network）
spring:
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: nacos-standalone:8848
        username: nacos
        password: nacOsdev316
  insight:
    server-url: http://insight-server:9966

server:
  address: 0.0.0.0
