spring:
  application:
    name: sca-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: order-service
          uri: lb://sca-order
          predicates:
            - Path=/order/**
        - id: product-service
          uri: lb://sca-product
          predicates:
            - Path=/product/**
        - id: user-service
          uri: lb://sca-user
          predicates:
            - Path=/user/**
        - id: loyalty-service
          uri: lb://sca-loyalty
          predicates:
            - Path=/loyalty/**
  insight:
    enabled: true
    service-name: sca-gateway

server:
  port: 8080
