# Resolve free host ports then start docker compose.
# Usage (repo root):
#   .\scripts\docker-up.ps1
#   .\scripts\docker-up.ps1 -Build
#   .\scripts\docker-up.ps1 -Build -Traffic
#   .\scripts\docker-up.ps1 -ResolveOnly
#
# 注意：insight-server 需已在宿主机单独启动（默认 http://localhost:9966/）。

param(
    [switch]$Build,
    [switch]$Traffic,
    [switch]$ResolveOnly,
    [int]$GatewayPrefer = 8080,
    [int]$OrderPrefer = 8081,
    [int]$SearchSpan = 40
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

function Test-PortBusy([int]$Port) {
    try {
        $listeners = Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue |
            Where-Object { $_.LocalPort -eq $Port }
        if ($listeners) { return $true }
    } catch { }

    $tcp = $null
    try {
        $tcp = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, $Port)
        $tcp.Start()
        return $false
    } catch {
        return $true
    } finally {
        if ($null -ne $tcp) {
            try { $tcp.Stop() } catch { }
        }
    }
}

function Find-FreePort([int]$Prefer, [System.Collections.Generic.HashSet[int]]$Reserved) {
    $end = $Prefer + $SearchSpan
    for ($p = $Prefer; $p -le $end; $p++) {
        if ($Reserved.Contains($p)) { continue }
        if (-not (Test-PortBusy $p)) {
            [void]$Reserved.Add($p)
            return $p
        }
    }
    throw "No free port in range $Prefer..$end"
}

$reserved = New-Object 'System.Collections.Generic.HashSet[int]'
$gatewayPort = Find-FreePort $GatewayPrefer $reserved
$orderPort = Find-FreePort $OrderPrefer $reserved

$portsFile = Join-Path $Root ".env.ports"
$lines = @(
    "# auto-generated by scripts/docker-up.ps1"
    "GATEWAY_HOST_PORT=$gatewayPort"
    "ORDER_HOST_PORT=$orderPort"
)
$lines | Set-Content -Path $portsFile -Encoding Ascii

Write-Host "Host port mapping:"
Write-Host ("  sca-gateway     http://localhost:{0}/" -f $gatewayPort)
Write-Host ("  sca-order       http://localhost:{0}/" -f $orderPort)
Write-Host "  insight-server  http://localhost:9966/  (external; start separately)"

if ($gatewayPort -ne $GatewayPrefer -or $orderPort -ne $OrderPrefer) {
    Write-Host "Preferred ports were busy; switched automatically (see .env.ports)" -ForegroundColor Yellow
}

if ($ResolveOnly) {
    Write-Host "Wrote $portsFile ; skip start."
    exit 0
}

$composeArgs = @("--env-file", ".env", "--env-file", ".env.ports")
if ($Traffic) {
    $composeArgs += @("--profile", "traffic")
}
$composeArgs += @("up", "-d")
if ($Build) {
    $composeArgs += "--build"
}

Write-Host ("docker compose {0}" -f ($composeArgs -join " "))
& docker compose @composeArgs
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host ""
Write-Host "Started. Examples:"
Write-Host "  UI     http://localhost:9966/   (external insight-server)"
Write-Host ("  traffic curl http://localhost:{0}/order/create?userId=1&productId=1" -f $gatewayPort)
