spring:
  application:
    name: sca-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:38848
  insight:
    # serviceName 默认取 spring.application.name；上报到独立监测中心
    server-url: http://localhost:9966

server:
  port: 18081
