spring:
  cloud:
    nacos:
      discovery:
        server-addr: sca-nacos:8848
        username: nacos
        password: nacos
  insight:
    # Docker 网络内访问监测中心
    server-url: http://insight-server:9966
    diagnostic-logs: false

server:
  address: 0.0.0.0
